                <div class="col-sm-8">
                    <div class="row">
                      <div class="col-sm-12">
                        <p>
                          <hr class="topoTitulo2">                               
                          <h3 class="Cabin Cinza-Chumbo tituloContato">
                            <small>SIMPLES NACIONAL</small>
                            <br>
                            <b class="Extra-Bold">PERCENTUAIS APLICADOS</b>
                          </h3>
                          <br>
                          <h3>Anexo I - Comércio</h3><p><b>Participantes: </b>empresas de comércio (lojas em geral)</p>
                          <table style="height: 289px;" border="1" width="750"><tbody><tr><td style="text-align: center;"><b>Receita Bruta Total em 12 meses</b></td><td style="text-align: center;"><b>Alíquota</b></td><td style="text-align: center;"><b>Quanto descontar do valor recolhido</b></td></tr><tr class="borda-esq-escura"><td style="text-align: center;">Até R$ 180.000,00</td><td style="text-align: center;">4%</td><td style="text-align: center;">0</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 180.000,01 a 360.000,00</td><td style="text-align: center;">7,3%</td><td style="text-align: center;">R$ 5.940,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 360.000,01 a 720.000,00</td><td style="text-align: center;">9,5%</td><td style="text-align: center;">R$ 13.860,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 720.000,01 a 1.800.000,00</td><td style="text-align: center;">10,7%</td><td style="text-align: center;">R$ 22.500,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 1.800.000,01 a 3.600.000,00</td><td style="text-align: center;">14,3%</td><td style="text-align: center;">R$ 87.300,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 3.600.000,01 a 4.800.000,00</td><td style="text-align: center;">19%</td><td style="text-align: center;">R$ 378.000,00</td></tr></tbody></table>                          
                          <br>
                          <h3>Anexo II – Indústria</h3><p><b>Participantes: </b>fábricas/indústrias e empresas industriais</p>
                          <table style="height: 301px;" border="1" width="750"><tbody><tr><td style="text-align: center;"><b>Receita Bruta Total em 12 meses</b></td><td style="text-align: center;"><b>Alíquota</b></td><td style="text-align: center;"><b>Quanto descontar do valor recolhido</b></td></tr><tr class="borda-esq-escura"><td style="text-align: center;">Até R$ 180.000,00</td><td style="text-align: center;">4,5%</td><td style="text-align: center;">0</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 180.000,01 a 360.000,00</td><td style="text-align: center;">7,8%</td><td style="text-align: center;">R$ 5.940,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 360.000,01 a 720.000,00</td><td style="text-align: center;">10%</td><td style="text-align: center;">R$ 13.860,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 720.000,01 a 1.800.000,00</td><td style="text-align: center;">11,2%</td><td style="text-align: center;">R$ 22.500,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 1.800.000,01 a 3.600.000,00</td><td style="text-align: center;">14,7%</td><td style="text-align: center;">R$ 85.500,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 3.600.000,01 a 4.800.000,00</td><td style="text-align: center;">30%</td><td style="text-align: center;">R$ 720.000,00</td></tr></tbody></table>
                          <br>
                          <h3>Anexo III – Serviços</h3><p><b>Participantes: </b>empresas que oferecem serviços de psicologia, acupuntura, podologia, academias, laboratórios, medicina e odontologia, instalação, reparos e manutenção, agências de viagens, lotéricas, escritórios de contabilidade, dentre outros.
                          <table style="height: 273px;" border="1" width="750"><tbody><tr><td style="text-align: center;"><b>Receita Bruta Total em 12 meses</b></td><td style="text-align: center;"><b>Alíquota</b></td><td style="text-align: center;"><b>Quanto descontar do valor recolhido</b></td></tr><tr class="borda-esq-escura"><td style="text-align: center;">Até R$ 180.000,00</td><td style="text-align: center;">6%</td><td style="text-align: center;">0</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 180.000,01 a 360.000,00</td><td style="text-align: center;">11,2%</td><td style="text-align: center;">R$ 9.360,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 360.000,01 a 720.000,00</td><td style="text-align: center;">13,5%</td><td style="text-align: center;">R$ 17.640,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 720.000,01 a 1.800.000,00</td><td style="text-align: center;">16%</td><td style="text-align: center;">R$ 35.640,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 1.800.000,01 a 3.600.000,00</td><td style="text-align: center;">21%</td><td style="text-align: center;">R$ 125.640,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 3.600.000,01 a 4.800.000,00</td><td style="text-align: center;">33%</td><td style="text-align: center;">R$ 648.000,00</td></tr></tbody></table>
                          <br>
                          <h3>Anexo IV – Serviços</h3><p><b>Participantes: </b>empresas que fornecem serviços de limpeza, vigilância, obras, construção de imóveis, serviços advocatícios, dentre outros.
                          <table style="height: 292px;" border="1" width="751"><tbody><tr><td style="text-align: center;"><b>Receita Bruta Total em 12 meses</b></td><td style="text-align: center;"><b>Alíquota</b></td><td style="text-align: center;"><b>Quanto descontar do valor recolhido</b></td></tr><tr class="borda-esq-escura"><td style="text-align: center;">Até R$ 180.000,00</td><td style="text-align: center;">4,5%</td><td style="text-align: center;">0</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 180.000,01 a 360.000,00</td><td style="text-align: center;">9%</td><td style="text-align: center;">R$ 8.100,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 360.000,01 a 720.000,00</td><td style="text-align: center;">10,2%</td><td style="text-align: center;">R$ 12.420,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 720.000,01 a 1.800.000,00</td><td style="text-align: center;">14%</td><td style="text-align: center;">R$ 39.780,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 1.800.000,01 a 3.600.000,00</td><td style="text-align: center;">22%</td><td style="text-align: center;">R$ 183.780,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 3.600.000,01 a 4.800.000,00</td><td style="text-align: center;">33%</td><td style="text-align: center;">R$ 828.000,00</td></tr></tbody></table>
                          <br>
                          <h3>Anexo V – Serviços</h3><p><b>Participantes: </b>empresas que fornecem serviços de auditoria, jornalismo, tecnologia, publicidade, engenharia, dentre outros
                          <table style="height: 276px;" border="1" width="750"><tbody><tr><td style="text-align: center;"><b>Receita Bruta Total em 12 meses</b></td><td style="text-align: center;"><b>Alíquota</b></td><td style="text-align: center;"><b>Quanto descontar do valor recolhido</b></td></tr><tr class="borda-esq-escura"><td style="text-align: center;">Até R$ 180.000,00</td><td style="text-align: center;">15,5%</td><td style="text-align: center;">0</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 180.000,01 a 360.000,00</td><td style="text-align: center;">18%</td><td style="text-align: center;">R$ 4.500,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 360.000,01 a 720.000,00</td><td style="text-align: center;">19,5%</td><td style="text-align: center;">R$ 9.900,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 720.000,01 a 1.800.000,00</td><td style="text-align: center;">20,5%</td><td style="text-align: center;">R$ 17.100,00</td></tr><tr class="borda-esq-escura"><td style="text-align: center;">De 1.800.000,01 a 3.600.000,00</td><td style="text-align: center;">23%</td><td style="text-align: center;">R$ 62.100,00</td></tr><tr class="borda-esq-clara"><td style="text-align: center;">De 3.600.000,01 a 4.800.000,00</td><td style="text-align: center;">30,50%</td><td style="text-align: center;">R$ 540.000,00</td></tr></tbody></table>
                         </p>
                         <br><br><br><br>
                      </div>
                    </div>
            </div>